import { expect, test } from "./fixtures";

test("el catálogo filtra, consulta referencias y espera la confirmación para guardar", async ({ home: page }, testInfo) => {
  if (testInfo.project.name === "celular") await page.setViewportSize({ width: 320, height: 740 });
  await page.goto("/inventario");
  await page.getByRole("link", { name: /^Alacena/ }).click();
  await page.getByRole("button", { name: "Agregar producto", exact: true }).first().click();
  await page.getByRole("button", { name: "Elegir del catálogo", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Básicos de casa", exact: true });
  await expect(dialog).toBeVisible();
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("catalogo.png"), animations: "disabled" });
  const filters = dialog.getByRole("group", { name: "Rubros del catálogo", exact: true });
  await filters.getByRole("button", { name: "Almacén y cocina", exact: true }).press("Space");
  await expect(filters.getByRole("button", { name: "Almacén y cocina", exact: true })).toHaveAttribute("aria-pressed", "true");
  await dialog.getByRole("textbox").fill("arroz");
  await expect(dialog.getByRole("status")).toHaveText("1 producto");
  await dialog.getByRole("button", { name: "Precio de referencia de Arroz", exact: true }).click();
  const reference = page.getByRole("region", { name: "Precio de referencia", exact: true });
  await expect(reference).toContainText("Referencia publicada:");
  await expect(reference).toContainText("Consulta:");
  await expect(reference).not.toContainText("2026-10-07");
  await expect(reference.getByRole("link")).toHaveAttribute("target", "_blank");
  await expect(reference.getByRole("button", { name: "Cerrar", exact: true })).toBeFocused();
  await reference.getByRole("button", { name: "Cerrar", exact: true }).press("Tab");
  await expect(reference.getByRole("link")).toBeFocused();
  await expect(page.getByRole("button", { name: "Ver detalle de Arroz", exact: true })).toHaveCount(0);
  const bounds = await reference.boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  expect(bounds!.y).toBeGreaterThanOrEqual(0);
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height);
  await page.screenshot({ path: testInfo.outputPath("referencia.png"), animations: "disabled" });
  await reference.getByRole("button", { name: "Cerrar", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Precio de referencia de Arroz", exact: true })).toBeFocused();
  await dialog.getByRole("button", { name: "Precio de referencia de Arroz", exact: true }).press("Enter");
  await expect(reference).toBeVisible();
  await dialog.getByRole("button", { name: "Precio de referencia de Arroz", exact: true }).press("Escape");
  await expect(reference).toBeHidden();
  await expect(dialog).toBeVisible();
  await dialog.getByRole("button", { name: /^Arroz paquetes/ }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole("textbox", { name: "Nombre", exact: true })).toHaveValue("Arroz");
  await expect(page.getByText("Arroz listo para revisar. Confirmá con Agregar.", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Ver detalle de Arroz", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Agregar", exact: true }).click();
  await expect(page.getByRole("button", { name: "Ver detalle de Arroz", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Agregar producto", exact: true }).first().click();
  await page.getByRole("button", { name: "Elegir del catálogo", exact: true }).click();
  // Cada alta empieza con el catálogo limpio.
  await expect(dialog.getByRole("textbox")).toHaveValue("");
  await dialog.getByRole("textbox").fill("arroz");
  await filters.getByRole("button", { name: "Herramientas", exact: true }).click();
  await expect(dialog.getByRole("status")).toHaveText("0 productos");
  await dialog.getByRole("button", { name: "Limpiar filtros", exact: true }).click();
  await expect(filters.getByRole("button", { name: "Todos los rubros", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(dialog.getByRole("textbox")).toHaveValue("");
  await filters.getByRole("button", { name: "Herramientas", exact: true }).click();
  await dialog.getByRole("textbox").fill("taladro");
  await dialog.getByRole("button", { name: "Precio de referencia de Taladro", exact: true }).click();
  await expect(reference).toContainText("Sin precio de referencia verificado.");
  await reference.getByRole("button", { name: "Cerrar", exact: true }).click();
  await dialog.getByRole("button", { name: /^Taladro unidades/ }).click();
  await expect(page.getByRole("switch", { name: /^Herramienta o equipo reutilizable/ })).toBeChecked();
  await expect(page.getByRole("switch", { name: /^Sugerir en la lista/ })).not.toBeChecked();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
});

test("las referencias se leen en inglés y conservan la fecha de consulta", async ({ home: page }, testInfo) => {
  if (testInfo.project.name === "celular") await page.setViewportSize({ width: 320, height: 740 });
  await page.goto("/ajustes");
  await page.getByText("English", { exact: true }).click();
  await page.goto("/inventario");
  await page.getByRole("link", { name: /^Alacena/ }).click();
  await page.getByRole("button", { name: "Add item", exact: true }).first().click();
  await page.getByRole("button", { name: "Choose from catalog", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Home essentials", exact: true });
  await dialog.getByRole("textbox").fill("rice");
  await dialog.getByRole("button", { name: "Reference price for Rice", exact: true }).click();
  const reference = page.getByRole("region", { name: "Reference price", exact: true });
  await expect(reference).toContainText("Published reference:");
  await expect(reference).toContainText("Oct 7, 2026");
  await expect(reference).toContainText("List price, excludes delivery.");
  await expect(reference).not.toContainText("Consulta:");
  await page.screenshot({ path: testInfo.outputPath("reference-en.png"), animations: "disabled" });
});
