import { expect, test } from "@playwright/test";

test("una casa vacía no incorpora lugares ni artículos y no vuelve a preguntar", async ({ page }) => {
  await page.goto("/empezar");
  await page.getByRole("button", { name: "Empezar acá" }).click();
  await expect(page.getByRole("checkbox", { name: "Heladera", exact: true })).toBeDisabled();
  await expect(page.getByRole("checkbox", { checked: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Empezar sin precarga" }).click();
  await page.getByText("Administrador", { exact: true }).first().click();
  await page.goto("/inventario");
  await expect(page.getByRole("textbox", { name: "¿Dónde guardé…?" })).toHaveCount(0);
  await expect(page.getByText("Alacena", { exact: true })).toHaveCount(0);
  await expect(page.getByText("Heladera", { exact: true })).toHaveCount(0);
  await page.goto("/empezar");
  await page.getByRole("button", { name: "Empezar acá" }).click();
  await expect(page).not.toHaveURL(/empezar/);
  await expect(page.getByRole("heading", { name: "¿Cómo querés empezar tu casa?" })).toHaveCount(0);
});

test("revisa un patrón, edita cantidades y excluye productos antes de guardarlos", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/empezar");
  await page.getByRole("button", { name: "Empezar acá" }).click();
  await page.getByRole("checkbox", { name: "Cocina", exact: true }).press("Space");
  await expect(page.getByRole("checkbox", { name: "Cocina", exact: true })).toBeChecked();
  await page.getByRole("checkbox", { name: "Heladera", exact: true }).check();
  // Ambientes y contenedores propios: entran seleccionados y vacíos.
  await page.getByRole("textbox", { name: "Nombre de otro ambiente" }).fill("Altillo");
  await page.getByRole("textbox", { name: "Nombre de otro ambiente" }).press("Enter");
  await expect(page.getByRole("checkbox", { name: "Altillo", exact: true })).toBeChecked();
  await page.getByRole("textbox", { name: "Nombre de otro contenedor" }).fill("Baúl");
  await page.getByRole("button", { name: "Agregar" }).nth(1).click();
  await page.getByRole("combobox", { name: "Ubicación de Baúl" }).click();
  await page.getByTitle("Altillo").click();
  await expect(page.getByRole("radio", { name: "Básicos a mano · mediados de mes" })).toHaveAccessibleDescription(/^Lo justo para el día a día\. Carga 9 artículos/);
  await page.getByRole("radio", { name: "Solo espacios, sin artículos", exact: true }).press("ArrowDown");
  await page.getByRole("radio", { name: "Compra completa · principio de mes", exact: true }).press("ArrowDown");
  await expect(page.getByRole("radio", { name: "Básicos a mano · mediados de mes" })).toBeChecked();
  await page.getByRole("button", { name: "Heladera", exact: true }).click();
  const eggs = page.getByRole("group", { name: "Cantidad de Huevos", exact: true });
  await eggs.getByRole("spinbutton").fill("0");
  await expect(eggs.getByRole("button", { name: "Restar uno" })).toBeDisabled();
  await eggs.getByRole("button", { name: "Sumar uno" }).click();
  await expect(eggs.getByRole("spinbutton")).toHaveValue("1");
  await page.getByRole("spinbutton", { name: "Cantidad de Huevos", exact: true }).fill("7");
  await page.getByRole("checkbox", { name: "Leche", exact: true }).uncheck();
  await expect(page.getByRole("group", { name: "Cantidad de Leche", exact: true }).getByRole("button", { name: "Sumar uno" })).toBeDisabled();
  await page.locator("fieldset").first().screenshot({ path: testInfo.outputPath("ambientes.png"), animations: "disabled" });
  await expect(page.getByText("Huevos blancos grandes · 6 ud.", { exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "DIA online · Argentina" }).first()).toHaveAttribute("href", /diaonline/);
  await page.screenshot({ path: testInfo.outputPath("precarga.png"), fullPage: true });
  await page.getByRole("button", { name: "Guardar esta selección" }).click();
  await page.getByText("Administrador", { exact: true }).first().click();
  await page.goto("/inventario");
  await expect(page.getByText("Taller de herramientas", { exact: true })).toHaveCount(0);
  await expect(page.getByText("Baúl", { exact: true }).first()).toBeVisible();
  await page.getByText("Heladera", { exact: true }).first().click();
  await expect(page.getByRole("button", { name: "Ver detalle de Leche", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Ver detalle de Huevos", exact: true }).click();
  await expect(page.getByText("7", { exact: true }).first()).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: "Ver detalle de Huevos", exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
