import { test, expect } from '@playwright/test';
import { addItem, selectTestSpaces, addNote } from './fixtures';

test('casas integradas: demo y pruebas conservan cambios sin tocar la casa habitual', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/empezar?house=home');
  await page.getByRole('button', { name: 'Empezar acá', exact: true }).click();
  await selectTestSpaces(page);
  await page.getByRole('heading', { name: 'Administrador', exact: true }).click();
  await page.goto('/inventario');
  await expect(page.getByRole('link', { name: /^Herramientas inventariadas/ })).toHaveCount(0);
  await addItem(page, 'Estantería de herramientas', 'Herramienta de mi casa habitual', 2, 0);
  const ordinarySession = await page.evaluate(() => localStorage.getItem('refugiar-session'));
  await page.goto('/ajustes');
  await page.getByRole('link', { name: 'Explorar casa demo', exact: true }).click();
  await page.getByRole('button', { name: 'Explorar casa demo', exact: true }).click();
  await page.getByRole('heading', { name: 'Administrador', exact: true }).click();
  await page.goto('/inventario');
  await page.getByRole('link', { name: /^Caja de recuerdos y piezas sueltas/ }).first().click();
  await addNote(page, 'Solo en demo, nunca en mi casa');
  await expect(page.getByText('Solo en demo, nunca en mi casa', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Casa demo · datos ficticios', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('demo-cambiar-casa.png'), animations: 'disabled' });
  await page.getByRole('link', { name: 'Abrir mi casa de pruebas', exact: true }).click();
  await page.getByRole('button', { name: 'Entrar a mi casa de pruebas', exact: true }).click();
  await page.getByRole('heading', { name: 'Administrador', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Casa de pruebas · datos ficticios', exact: true })).toBeVisible();
  await page.goto('/inventario');
  await page.getByRole('link', { name: /^Caja de recuerdos y piezas sueltas/ }).first().click();
  await expect(page.getByText('Solo en demo, nunca en mi casa', { exact: true })).toHaveCount(0);
  await page.goto('/recetas');
  await expect(page.getByText('Pizza de la familia', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Casa de pruebas · datos ficticios', exact: true }).click();
  await page.getByRole('link', { name: 'Explorar casa demo', exact: true }).click();
  await page.getByRole('button', { name: 'Explorar casa demo', exact: true }).click();
  await page.goto('/inventario');
  await page.getByRole('link', { name: /^Caja de recuerdos y piezas sueltas/ }).first().click();
  await expect(page.getByText('Solo en demo, nunca en mi casa', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Casa demo · datos ficticios', exact: true }).click();
  await page.getByRole('link', { name: 'Volver a mi casa', exact: true }).click();
  await page.goto('/inventario');
  await expect(page.getByRole('link', { name: /^Herramientas inventariadas/ })).toHaveCount(0);
  await page.getByText('Estantería de herramientas', { exact: true }).first().click();
  await expect(page.getByRole('button', { name: 'Ver detalle de Herramienta de mi casa habitual', exact: true })).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem('refugiar-session'))).toBe(ordinarySession);
  expect(errors).toEqual([]);
});
